const SECTION_5_DATA = {
    questions: [
        { q: "Ecologists try to find out how the Earth's environments can be preserved _____ living things will continue to survive on the planet.", opts: ["now that","in order to","in case","so that"] },
        { q: "_____ children get older, their questions get harder to answer.", opts: ["As","Because of","In order that","However"] },
        { q: "It is easier to study animals and plants than human beings, _____ plant and animal behaviors can be controlled and monitored.", opts: ["thus","due to","because","however"] },
        { q: "Milk must be moved rapidly from the farm to the consumer and kept cold _____ it will not spoil.", opts: ["so as","in case","if","so that"] },
        { q: "Experts estimate that we are losing 137 plant, animal and insect species every single day _____ rainforest deforestation.", opts: ["as","while","so","due to"] },
        { q: "_____ you left, the atmosphere in the office has not been as nice.", opts: ["When","Although","Since","So that"] },
        { q: "_____ you already know Mary, you should go to meet her at the airport.", opts: ["Although","Since","When","In spite"] },
        { q: "_____ we would like to open a branch in Oxford now, we will probably wait for another year or so.", opts: ["When","Since","Although","Due to"] },
        { q: "This job is badly paid, _____ I'm looking for another one.", opts: ["because","so","since","as"] },
        { q: "We're not making much profit _____ we need to raise our prices.", opts: ["because","since","though","so"] },
        { q: "I need to get to work early _____ I can finish the report before the meeting.", opts: ["despite","so that","when","since"] },
        { q: "Adams was dismissed from his job _____ he kept improper financial records.", opts: ["for","despite","because of","so that"] },
        { q: "California relies heavily on income from fruit crops _____.", opts: ["but Florida does so","and so does Florida","as though Florida doesn't do","in spite of Florida does so"] },
        { q: "It is very difficult to stop the cultivation of weed _____ it grows well with little care.", opts: ["however","nevertheless","because","though"] },
        { q: "Mr. Robert is a noted chemist _____.", opts: ["in spite of being an efficient teacher","because of an efficient teacher","but also an efficient teacher","as well as an efficient teacher"] },
        { q: "Her grades have improved, _____ very slightly.", opts: ["as if","so that","but only","despite"] },
        { q: "The students liked that professor's course _____ there was little or no homework.", opts: ["nevertheless","however","because of","because"] },
        { q: "_____ its durability and economy, the best car to buy is a Mercedes Benz.", opts: ["Because of","In spite of","As if","So that"] },
        { q: "I don't know him very well, _____ I have met him once or twice.", opts: ["in spite","as if","although","however"] },
        { q: "The committee rejected the proposal _____ they did not think it was practical.", opts: ["however","because","though","nevertheless"] },
        { q: "He refused to give up work, _____ he had won a million pounds.", opts: ["despite","however","even though","as though"] },
        { q: "The children won't go to sleep _____ we have a light on outside their bedroom.", opts: ["except","otherwise","unless","but"] },
        { q: "_____ Patrick, he can't possibly go alone – he's far too young.", opts: ["As if","As","As for","As far as"] },
        { q: "You can use my bicycle _____ you promise to bring it back tomorrow.", opts: ["as long as","although","nevertheless","in spite of"] },
        { q: "She wonders _____ her father looks like now, after so many years away.", opts: ["how","whose","that","what"] },
        { q: "Many people don't drink coffee in the evening _____ it keeps them awake.", opts: ["therefore","however","so that","because"] },
        { q: "I'll keep trying different jobs _____ I have found a career I really enjoy.", opts: ["until","when","while","as soon as"] },
        { q: "Bats do not have good eyesight, _____ they have to hunt for their food during the night.", opts: ["as a matter of fact","despite","although","for"] },
        { q: "An example of a nice dream is when we are doing something successfully, _____ a common nightmare is when we are making fools of ourselves.", opts: ["because","while","so","that"] },
        { q: "It doesn't matter which restaurant we choose _____ the service is good.", opts: ["on condition","as soon as","so long as","so that"] },
        { q: "Tobacco is bad for health, _____ many people all over the world continue to smoke it.", opts: ["yet","because","that","so that"] },
        { q: "Here is the CD _____ you asked me to bring.", opts: ["which","what","whom","where"] },
        { q: "_____ you take a mobile phone into the examination room, your teacher will punish you.", opts: ["Even if","Although","If","Unless"] },
        { q: "Primitive people had many superstitions about the owl, _____ the strange sounds it makes.", opts: ["apart from","because","since","because of"] },
        { q: "You should buy a good road map _____ you start your journey.", opts: ["after","before","ever since","while"] },
        { q: "Most of the older civilizations _____ flourished during the fifth century BC have died out.", opts: ["how","what","which","where"] },
        { q: "_____ around 8000 B.C., mammoths became extinct.", opts: ["With the end of the Ice Age","It was the end of the Ice Age that","That the end of the Ice Age","In addition to the end of the Ice Age"] },
        { q: "A bat will often spend the daylight hours _____ in a tree or cave.", opts: ["hanging upside down","which hangs upside down","that is upside down","while hanging upside down"] },
        { q: "A hero of the war of 1812, _____ the president of the United States.", opts: ["that Andrew Jackson later became","Andrew Jackson later became","who was Andrew Jackson","later became Andrew Jackson"] },
        { q: "_____ in Japan as after that terrible earthquake.", opts: ["Never the situation was so serious","Not only was the situation so serious","Never was the situation so serious","No sooner had the situation been so serious"] },
        { q: "_____ a large part of western Utah was covered by Lake Bonneville.", opts: ["In Prehistoric times","It was in Prehistoric times","Because it was in Prehistoric times","As in Prehistoric times is"] },
        { q: "She behaves _____ she were the boss of the company and the staff obeys her humbly.", opts: ["as though","as long as","even though","as"] },
        { q: "He is working hard _____ he can get a better and more interesting job.", opts: ["when","so that","although","as soon as"] },
        { q: "We have nothing to fear _____ our country is strong and united.", opts: ["for","whereas","though","although"] },
        { q: "It's not the best dictionary you can buy, _____ it's better than nothing.", opts: ["since","because of","but","despite"] },
        { q: "Mike is always on time _____ his brother is late at least twice a week.", opts: ["whereas","wherever","whenever","whatever"] },
        { q: "The food is not as good as it was. _____ they have put the prices up.", opts: ["In spite of","Despite","Since","In addition"] },
        { q: "It's busy during the week. At the weekend, _____, it is very quiet.", opts: ["however","besides","as long as","moreover"] },
        { q: "They told us the shop was next to the station. We never found it, _____.", opts: ["too","as well","though","despite"] },
        { q: "_____ wanting to see him again, she refused to reply to his letters.", opts: ["Although","In spite","Despite","Though"] },
        { q: "His first acting role, _____ small, was a great success.", opts: ["though","how","despite","inspite of"] },
        { q: "_____ the problems they had to grapple with, they still enjoyed the trip.", opts: ["Despite of","In spite of","Since","Although"] },
        { q: "I just want to assure you that _____ is the truth.", opts: ["what I tell you","in addition I tell you","because what I tell you","whether I tell you or not"] },
        { q: "I talked to George yesterday. _____ he would not admit his mistake.", opts: ["Even then","Even if","Even","As if"] },
        { q: "We thought she was rather arrogant, _____, in fact, she was just very shy.", opts: ["since","although","in spite","whereas"] },
        { q: "Some people protest certain commercial fishing operations, _____ dolphins, considered to be highly intelligent mammals, are killed unnecessarily.", opts: ["because","in addition","lest","whereas"] },
        { q: "_____ the earthquake damaged the bridge across the Skunk River, the Smiths were able to cross the river because they had a boat.", opts: ["Even if","Even though","In spite of","Despite"] },
        { q: "\"I do not like the shape of the hat, _____ I like its colour.\"", opts: ["since","despite","because","though"] },
        { q: "The adder is a very dangerous snake _____ bite may prove fatal to humans.", opts: ["as","whom","that","whose"] },
        { q: "_____ were first viewed through a telescope by Galileo.", opts: ["Jupiter has four moons","Jupiter's four moons","Jupiter surrounded by four moons","Surrounded by four moons, Jupiter"] },
        { q: "_____ her father's advice, Sarah Daole chose medicine as her course of studies.", opts: ["Although","Until","Despite","In spite"] },
        { q: "When travelling it is advisable to write your name and address on your bag _____ you lose it.", opts: ["unless","if","when","in case"] },
        { q: "Yesterday Jack was having a party but Sheila couldn't come, _____ was a pity.", opts: ["this","which","it","what"] },
        { q: "_____ you water the flowers every day and take care of them the garden will soon become a pleasant place.", opts: ["Provided that","Until","Nevertheless","Even if"] },
        { q: "Spiders are not insects, as many people think. _____, they are not even related to them.", opts: ["Even though","Consequently","Moreover","However"] },
        { q: "_____ about the need to educate people on recycling, the speaker stressed the importance of conserving paper.", opts: ["During talking","While talking","As talking","In the event of talking"] },
        { q: "Prospectors rushed to Nevada in 1859 _____ was discovered.", opts: ["while gold","soon after gold","gold where","so gold that"] },
        { q: "Michelson, _____ carried out experiments on the speed of light, was the first American to receive a Nobel Prize in science.", opts: ["whom","who","that","which"] },
        { q: "_____ being the outer protective covering of the body, the skin performs many other necessary functions.", opts: ["Beside","Besides","Although","Despite"] },
        { q: "A metaphor, _____, compares two things that are different, but have something in common.", opts: ["often used in poetry","has used in poetry","is used in poetry","has uses in poetry"] },
        { q: "He came as soon as he could _____ to help me complete the work by midnight.", opts: ["so that","provided that","so as","so"] },
        { q: "She is a good specialist. _____, I didn't hesitate to ask her for help.", opts: ["So that","Although","Even though","Therefore"] },
        { q: "_____ it was late and our children had already gone to bed, we didn't feel tired and sleepy.", opts: ["Because","Although","In spite of","As"] },
        { q: "I like travelling by ship _____ the sea is not rough.", opts: ["as long as","unless","despite","in case"] },
        { q: "When I was strolling by the Nile, I suddenly saw someone _____ photo I had seen in the newspaper.", opts: ["whom","who","whose","which"] },
        { q: "_____ Henry had looked through all the drawers in his room he started going through the cupboards downstairs.", opts: ["When","Meanwhile","While","Afterwards"] },
        { q: "One solution to the problem of deforestation is to use less paper, _____ fewer trees will be cut for paper making.", opts: ["though","in contrast","so that","yet"] },
        { q: "_____ its small store of words, Old English was a remarkably flexible language.", opts: ["Despite","In spite","Despite of","Although"] },
        { q: "I was shocked _____ what I had done.", opts: ["when I realized","when I realized that","as I realized that","when realizing that"] },
        { q: "This man lives in a country _____.", opts: ["and they speak two languages","where they speak two languages","that's why they speak two languages","in which two languages speak"] },
        { q: "You look so frightened! It seems _____ you have seen a ghost.", opts: ["as","if","as though","although"] },
        { q: "I am afraid _____ until tomorrow.", opts: ["there is no chance of seeing the director","it is no chance to see the director","there isn't no chance of seeing the director","it will be any chance of seeing the director"] },
        { q: "_____, we seldom see each other.", opts: ["Now when Henry lives in Boston","Now that Henry lives in Boston","No matter if Henry lives in Boston","Now then Henry lives in Boston"] },
        { q: "Millions of people around the world continue to smoke _____.", opts: ["in spite of the fact that smoking causes cancer","due to the fact that smoking causes cancer","even though the fact that smoking causes cancer","because smoking causes cancer"] },
        { q: "_____, the government has decided not to fund it.", opts: ["When they see that the scheme is likely to fail","While seeing that the scheme is likely to fail","To see that the scheme is likely to fail","Seeing that the scheme is likely to fail"] },
        { q: "A bridge collapsed last Monday _____ which hit Southern California.", opts: ["as a result of an earthquake","resulting in an earthquake","causing an earthquake","so that there was an earthquake"] },
        { q: "You had better lock all the doors, _____ you will be in trouble.", opts: ["in case of","provided that","so that","otherwise"] },
        { q: "I'm looking forward to seeing the Pyramids _____ we visit Egypt.", opts: ["whenever","when","by which","since when"] },
        { q: "Drinking wine in a dream means that you will experience happiness, _____ drinking beer means that you will be disappointed.", opts: ["therefore","whereas","as far as","for"] },
        { q: "I don't know _____ my grandfather manages to live on his small pension.", opts: ["how","why","that","what"] },
        { q: "The coach was full and the weather very hot, but the air conditioning wasn't working. _____, the passengers were uncomfortable and many of them complained.", opts: ["Nevertheless","Consequently","Otherwise","Furthermore"] },
        { q: "_____ than he began to feel sleepy.", opts: ["He had no sooner drunk the coffee","He no sooner had drunk the coffee","Hardly had he drunk the coffee","He had hardly drunk the coffee"] },
        { q: "Since the documents haven't arrived _____.", opts: ["we can't load the goods","we couldn't load the goods","we should load the goods","we will load the goods"] },
        { q: "Although the pension was very reasonably priced, it was certainly not uncomfortable. _____, it had a beautiful shady garden and a roof terrace with a splendid view of the area.", opts: ["Therefore","Even though","Otherwise","Moreover"] },
        { q: "_____ the heavy rain, we greatly enjoyed ourselves.", opts: ["In spite","Though","Despite","However"] },
        { q: "Tom was very persuasive, _____, I did what he asked.", opts: ["provided","in order","moreover","accordingly"] },
        { q: "_____ they live near the Browns, they see them quite seldom.", opts: ["Although","As","As soon as","Still"] },
        { q: "There is fog at the airport, _____ the plane has been diverted.", opts: ["therefore","though","in contrast","nevertheless"] },
        { q: "The professor said that _____ on Monday.", opts: ["if the students could hand in their reports","when the students could hand in their reports","why the students could hand in their reports","the students could hand in their reports"] },
        { q: "Not only _____, they serve for scientific and educational purposes as well.", opts: ["are botanical gardens places of beauty but also","are botanical gardens places of beauty","botanical gardens being places of beauty","botanical gardens are places of beauty but"] },
        { q: "When _____ is not known.", opts: ["inventing the wheel","was the wheel invented","the invention of the wheel","the wheel was invented"] },
        { q: "The type of clothing people wear tells others a lot about _____.", opts: ["who are they","who they are","where they are","where are they"] },
        { q: "They know the risks of swimming with sharks, _____ they insist on doing it.", opts: ["accordingly","consequently","yet","as a result"] },
        { q: "Most folk songs are ballads _____ have simple words and tell simple stories.", opts: ["that","what","who","when"] },
        { q: "Parrots can live in temperate or even cold climates, _____ they are tropical birds.", opts: ["but","despite","even though","nevertheless"] },
        { q: "Owls can hunt in total darkness _____ their remarkably keen sense of smell.", opts: ["however","since","because of","therefore"] },
        { q: "The tennis match planned for tomorrow will take place _____.", opts: ["as if it was raining","and it doesn't rain","but it doesn't rain","as long as it doesn't rain"] },
        { q: "He had no sooner opened the door of his flat _____.", opts: ["as if something strange he felt","then he felt something strange","if he felt something stranger","than he felt something strange"] },
        { q: "I didn't agree with him _____.", opts: ["so I went on listening to him willingly","though I didn't listen to him","but I went on listening to him willingly","if I didn't listen to him"] },
        { q: "The household vacuum cleaner was first mass-produced by William Henry Hoover; _____, it is now commonly referred to as a 'hoover'.", opts: ["besides","otherwise","whereas","therefore"] },
        { q: "_____ smoking can cause lung problems, many people all over the world smoke.", opts: ["Despite","Because","As","Although"] },
        { q: "Your mother will punish you, _____ you go home late.", opts: ["unless","although","if","because of"] },
        { q: "Primitive people had many superstitions about the owl _____ the strange sounds it makes.", opts: ["because of","because","since","apart from"] },
        { q: "Not only was the president dedicated to fighting poverty _____ to put an end to racial discrimination.", opts: ["but he vowed as well as","that he vowed too","but he also vowed","also he vowed"] },
        { q: "_____ I dislike sentimental films, sometimes, when I'm not feeling very energetic, I can curl up on the sofa and watch one.", opts: ["As soon as","Though","However","Despite"] },
        { q: "She is fed up with sharing a house with others; _____, she is looking for her own flat.", opts: ["moreover","therefore","although","nevertheless"] },
        { q: "He is not leaving the company because he is unhappy there; _____, he has enjoyed working there, but he has other reasons.", opts: ["on the other hand","however","on the contrary","nevertheless"] },
        { q: "She had _____ placed the plate of cakes on the table _____ the children gave her the empty plate and requested some more.", opts: ["the moment/while","hardly/when","neither/nor","not only/but also"] },
        { q: "_____ how many windows I open, I can't get any air movement in the house.", opts: ["Even if","Although","No matter","Whereas"] },
        { q: "We had better take a spare blanket with us _____ it gets cooler than we expect in the mountains.", opts: ["if only","so that","in case","even though"] },
        { q: "_____ they played better than they have so far, they lost the match.", opts: ["Despite","No sooner","However","Although"] },
        { q: "_____ to relieve some of the burden on the city's only airport, they are planning to build a second one.", opts: ["No matter","In case","In order","Even though"] },
        { q: "Our students have to choose to study _____ French _____ Spanish, because they are the compulsory languages selected by the board.", opts: ["neither…nor","scarcely…and","whether….or","either…or"] },
        { q: "_____ we discuss the details, let me ask you whether you are interested in our offer.", opts: ["Consequently","Afterwards","In spite of","Before"] },
        { q: "Western Scotland is wild and mountainous, _____ eastern Scotland is lush farmland.", opts: ["despite","whereas","nevertheless","therefore"] },
        { q: "I don't see why the boys can't go fishing _____ they promise to stay together and come back before it gets dark.", opts: ["whereas","no matter","whether","as long as"] },
        { q: "_____ the solar system is tiny compared with the distances to galaxies or even to nearby stars, it is enormous when compared with distances on the Earth.", opts: ["Even though","Nevertheless","As long as","The fact that"] },
        { q: "He was extremely happy about winning the contest, because it gave him not only the opportunity to join a professional orchestra, _____ the chance to travel.", opts: ["but as well","and","but also","and also"] },
        { q: "Not only does the International Students' Society help foreign students settle in, _____ it organizes sightseeing trips as well.", opts: ["so that","but also","but","on the contrary"] },
        { q: "_____ 'Internet Cafes', students who can't afford computers have access to the Internet and to e-mail.", opts: ["In order that","Owing to","Wherever","Whereas"] },
        { q: "Black bears don't usually attack humans. _____, they normally run away from us.", opts: ["On the contrary","On the other hand","Furthermore","Consequently"] },
        { q: "She has been looking much more enthusiastic about the future _____ she accepted her new job.", opts: ["since","until","before","when"] },
        { q: "_____ the renovation of their football stadium, the team will be using another team's ground next season.", opts: ["However","While","Due to","Because"] },
        { q: "Please answer the telephone for the next hour _____ the receptionist has gone to the dentist.", opts: ["while","until","so","as"] },
        { q: "The residents received some warning of the tornado; _____, several people were injured.", opts: ["nevertheless","despite","even though","thus"] },
        { q: "He was tired of commuting such a long way to work, _____ he was quite excited when a local company offered him a job.", opts: ["so","for","though","still"] },
        { q: "It was clear that _____ how much he protested, his father was not going to change his mind.", opts: ["no matter","whereas","whenever","although"] },
        { q: "_____ it was extremely windy, we managed to have a good game of beach volleyball.", opts: ["However","No matter","In spite of","Even though"] },
        { q: "We are going to set out at dawn tomorrow, _____ we have loaded up the car tonight.", opts: ["when","so","for","because"] },
        { q: "His parents were happy that he managed to gain a university degree _____ his handicap.", opts: ["provided","besides","though","despite"] },
        { q: "I have heard that he has been doing well _____ he opened his own language school.", opts: ["since","no sooner","when","by the time"] },
        { q: "He had no sooner opened the doors of the shop _____ a customer came in and bought all the fresh cream cakes.", opts: ["when","that","where","than"] },
        { q: "I like to read my newspaper _____ travelling to work, but I often leave it behind.", opts: ["while","as soon as","because of","since"] },
        { q: "_____ you have used the photocopier, please don't forget to turn it off.", opts: ["After","Just","Before","Unless"] },
        { q: "People often don't tell the truth on market surveys; _____, the results obtained from them are not always accurate.", opts: ["for","otherwise","due to","thus"] },
        { q: "The police are determined to find the culprits _____ long it may take to trace them.", opts: ["in spite of","however","even if","no matter"] },
        { q: "The people of Quebec, Canada, are so patriotic _____ the blue and white provincial flag flies over many homes and businesses.", opts: ["but","although","because","that"] },
        { q: "_____ for our coffee break, the fire alarm rang.", opts: ["Hardly we sat down","Sitting down","As long as sitting down","Just as we sat down"] },
        { q: "_____ being an accomplished artist, Leonardo da Vinci was also a sculptor, an architect and a man of science.", opts: ["Not only","However","Besides","Moreover"] },
        { q: "_____ the great diversity in social behaviour and habits between different types of ants, most of them have the same basic physical structure.", opts: ["Regardless","As if","Besides","Despite"] },
        { q: "Strawberries are so cheap at the moment _____ we should make some jam.", opts: ["because","that","so that","while"] },
        { q: "This book is neither entertaining nor informative, _____ I definitely recommend it to you.", opts: ["but","although","because","so"] },
        { q: "Some people argue that traditional blood sports, _____ fox-hunting and bullfighting, should be banned because they are barbaric and inhumane.", opts: ["in case","as far as","such as","as though"] },
        { q: "Peter is leaving to go back to England, _____ we are holding a farewell dinner for him.", opts: ["or else","since","yet","so"] },
        { q: "As we will be touring, we could take the tent just _____ we see a nice campsite and want to stop.", opts: ["in case","unless","until","as"] },
        { q: "_____ the work was physically demanding, and at times we felt really exhausted, seeing the end result was very satisfying.", opts: ["Owing to","Even though","No matter","As though"] },
        { q: "They looked around a lot of different buildings _____ they could choose the most suitable one to rent for their new business.", opts: ["yet","besides","since","so that"] },
        { q: "I wasn't disappointed when I lost, _____, I hadn't even expected to get as far as I had in the competition.", opts: ["consequently","though","moreover","providing"] }
    ],
    answers: [
    3, 0, 2, 3, 3, 2, 1, 2, 1, 3, // 1-10
    1, 0, 1, 2, 3, 2, 3, 0, 2, 1, // 11-20
    2, 2, 2, 0, 3, 3, 0, 2, 1, 2, // 21-30
    0, 0, 2, 3, 1, 2, 0, 0, 1, 2, // 31-40
    0, 0, 1, 0, 2, 0, 3, 0, 2, 2, // 41-50
    0, 1, 0, 0, 3, 0, 1, 3, 3, 1, // 51-60
    2, 3, 1, 0, 2, 1, 1, 1, 1, 0, // 61-70
    2, 3, 1, 0, 2, 0, 2, 0, 1, 1, // 71-80
    2, 0, 1, 0, 3, 0, 3, 1, 1, 0, // 81-90
    1, 0, 0, 3, 2, 3, 0, 0, 3, 1, // 91-100
    3, 1, 2, 0, 2, 2, 3, 3, 2, 3, // 101-110
    3, 2, 0, 2, 1, 1, 2, 1, 2, 3, // 111-120
    3, 2, 3, 3, 1, 3, 0, 2, 2, 1, // 121-130
    0, 0, 2, 3, 0, 0, 0, 3, 1, 3, // 131-140
    0, 3, 0, 0, 3, 1, 3, 3, 2, 3, // 141-150
    1, 0, 2, 3, 0, 1, 3, 2, 3, 1  // 151-160
]

};