const ALL_Q = [
  {opts:["Why do you think he flunked the exam?","Let's take a taxi, shall we?","You'd rather go there by train, hadn't you?","Is Mary or are you going to cooperate with Debbie?","His wife has headaches quite often, doesn't she?"],correct:[0,1,3,4]},
  {opts:["Do you have any idea where he comes from?","He had a smoke every ten minutes, hadn't he?","She does not believe in what she cannot see, does she?","How often did you visit museums when were you in London?","This is a nice place to have a picnic, isn't this?"],correct:[0,2]},
  {opts:["Don't you think St. Petersburg is a clean city?","Can you tell me why do you take English classes?","There are a lot of fruit trees in their orchard, aren't they?","He's been working on this project since last year, hasn't he?","Do you think my pronunciation has improved?"],correct:[0,3,4]},
  {opts:["Did she feel better after she took a nap?","Do you know who invented the telescope?","This is the second time you have escaped from classes, isn't it?","Will you come to the nightclub tomorrow or to stay at home?","She has to buy an evening dress for the party, doesn't she?"],correct:[0,1,2,4]},
  {opts:["What does the first Amendment guarantee?","Do you think you can achieve happiness by avoiding negative feelings?","He's to interview a foreign delegation today, hasn't he?","Have you read how many houses did the tornado destroy?","What do you think he appreciates in a person most?"],correct:[0,1,4]},
  {opts:["How do the students intend to demonstrate against the new regulations?","Did you know that the inventors of cinema were French?","George Washington was the first US president, wasn't he?","Do you think has my English improved?","You had the ceiling whitewashed, hadn't you?"],correct:[0,1,2]},
  {opts:["When did you find out that the bath had overflowed?","Do you have any idea who won the scholarship?","I think everybody likes ice-cream, don't they?","What should the responsibilities of teachers be?","Is this the first time you have won a prize, isn't it?"],correct:[0,1,2,3]},
  {opts:["Do seldom you go to the swimming-pool?","A good speaker must be able to hold the attention of the audience, isn't?","Who do you think are the most superstitious people in the world?","What does make Karlovy Vary unique?","I'm a better dancer now than I was a year ago, am I not?"],correct:[2,4]},
  {opts:["Why did the United Nations plan to investigate the outbreak of TB?","Do you know where board members meet to develop new strategies?","Was the economic life of Africa centered in the Sudan?","Mary's got a nice cottage in the country, doesn't she?","What do you think how can you achieve health and happiness?"],correct:[0,1,2,3]},
  {opts:["David and Mike sent an anniversary card to their parents, didn't he?","What do you think we should buy for Mother on her birthday?","Did you know that the black widow is the most dangerous spider living in the US?","Do you enjoy having a wide circle of acquaintances?","Do you know what type of account does the woman want?"],correct:[1,2,3]},
  {opts:["Haven't you done your homework yet?","Are you sure you don't want to go to the movies tonight?","Are you more interested in a general idea than in the details of its realization?","Do you know why did the publishing houses appreciate him highly?","There are plenty of glasses in the cupboard, aren't they?"],correct:[0,1,2]},
  {opts:["Why do you think objective criticism is always useful in any activity?","The coffee tastes extremely good, doesn't it?","Would you like to have a cup of coffee with me?","Who did allow you to touch these things?","He'd better buy a new computer, hadn't he?"],correct:[0,1,2]},
  {opts:["Can you tell the class where comes chocolate from?","Do you know how was the name California first used?","Do you find it funny when I do my mute exercises with a mirror?","It's time for them to swim ashore, hasn't it?","Did you hear about the fire down the street?"],correct:[2,4]},
  {opts:["How much was the stove you bought yesterday?","Is it in your nature to assume responsibility?","Would you like to go to bed early or going to the pub with us?","John thinks I will help them with that work, doesn't he?","Who did look after the children while Mrs. Smith went shopping?"],correct:[0,1,3]},
  {opts:["He has to visit his sick friend today, doesn't he?","Is there a website that can explain why leaves change color in the fall?","Do you know what does the new computer program provide?","Does anybody know where was first played the game of golf?","Sam will scarcely want to take up this job, will he?"],correct:[0,1,4]},
  {opts:["Did you see yesterday anybody shoplifting?","Do you know where the president and his family are staying?","Which test do you think is more difficult: the TOEFL or the GRE?","Their family are early risers, don't they?","How old was your sister when she began to talk?"],correct:[1,2,4]},
  {opts:["Why did you return the vacuum-cleaner you bought yesterday?","What do you think he means by these words?","Didn't she to the shopping centre go yesterday?","It's hardly snowed this winter, has it?","Ted couldn't speak English well when he was a first-year student, wasn't he?"],correct:[0,1,3]},
  {opts:["Do you take the train to go to work?","The poor harvest caused prices to rise abruptly, didn't it?","Was it you or your brothers who repaired the road?","Do you know how long did the baby-sitter look after the children?","This is the second time Ted has been fined, isn't this?"],correct:[0,1,2]},
  {opts:["Are you sure do the great majority of tornadoes occur in the US?","Do you often think about mankind and its destiny?","Isn't it hard to drive downtown to work?","Do you have any idea why did he conceal the facts?","He'd changed a lot after the operation, wouldn't he?"],correct:[1,2]},
  {opts:["Do you remember what did the lecturer say about early teachers?","Is Cambridge University as old as the University of Oxford?","How long had you studied English before you took the TOEFL test?","When are you planning to send the memo to the staff?","The body depends on food as its primary source of energy, isn't it?"],correct:[1,2,3]},
  {opts:["He had the kitchen knives sharpened, didn't he?","How did you like my new apartment?","Do you think was he surprised to see her in the hotel?","Has been Ted working for this corporation for two years?","The twins cry all night, aren't they?"],correct:[0,1]},
  {opts:["Mark's got a nice motor-bike, isn't he?","John had his laptop repaired, hadn't he?","Are you going to Palm Springs or to Palm Beach?","Can you tell me what do Armenians usually have for breakfast?","Are checks and balances an important concept in the formation of the US system of government?"],correct:[2,4]},
  {opts:["Is it the second time you have taken this test, isn't it?","What do you do that is good for your mental health?","There's been a lot of snow recently, isn't there?","How many hours a day do the sportsmen have to train?","Is Sarah considered to be the best player in your team?"],correct:[1,2,3,4]},
  {opts:["Did they make the enemy withdraw the troops from the city or not?","Coldrex is considered to reduce temperature or not?","Your brother's fond of westerns, hasn't he?","There's hardly any money left, is there?","Did you use to live in a house before you moved into this flat?"],correct:[0,3,4]},
  {opts:["Which University does your elder sister study at?","Is the church at the end of the street catholic or it isn't?","How do you get to school: by car or on foot?","He's been working in this company for six years, isn't he?","I am slenderer now than I was three years ago, aren't I?"],correct:[0,2,4]},
  {opts:["I suppose everybody likes this author, don't I?","Which of you would like to take part in the race?","There's somebody waiting for you, hasn't there?","The rugby match was postponed, wasn't it?","Is it you who wants to speak to the boss?"],correct:[1,3,4]},
  {opts:["Do you think the owl can see at night?","Are the children back from school yet?","This fast car can do 350 kilometers an hour, can't this?","How many times have you been to that museum?","Did you sign yesterday the contract?"],correct:[0,1,3]},
  {opts:["He's got a web camera on his mobile phone, doesn't he?","Let's go to Scotland in July, will you?","Can your brother render this text in English or you can?","Aren't you fed up with eating bacon and eggs every morning?","Do you think we are doing the right thing?"],correct:[3,4]},
  {opts:["Why do most people on holiday go in summer?","The most unusual animals can be seen in this zoo, don't they?","Why do you think Ruby wants to talk to me?","Do you think horses eat lobsters?","You'd like to see Speaker's Corner in Hyde Park, wouldn't you?"],correct:[0,2,3,4]},
  {opts:["This kind of weather gets people down, doesn't it?","I am a better programmer now than I was two years ago, am not I?","Do you have any idea what vegetables grow in this part of the country?","What do you think he has to do to return her?","It's twelve years since they moved to this district, isn't it?"],correct:[0,2,3,4]},
  {opts:["Hasn't been Janet trying to improve her Spanish since last year?","Is there a good hotel in the neighbourhood or there isn't?","You'd never been to a rainforest before, had you?","Would anyone care to respond to the last question?","Will the people react against the political system that oppresses them?"],correct:[2,3,4]},
  {opts:["How long have they been trying that problem to solve?","The police broke the door down, didn't they?","Isn't it strange that he didn't respond to that question?","Annie's got a lot of English books, hasn't she?","What do you think is he ready to take a decisive step?"],correct:[1,2,3]},
  {opts:["Does Julia at 11 o'clock have a break for lunch or not?","He's got all the modern conveniences in his house, doesn't he?","Do you know why he wants to take an extended leave of absence?","You won't be able to change anything, will you?","Where did you last month travel?"],correct:[1,2,3]},
  {opts:["He's had a lot of trouble with her lately, hasn't he?","How do you think she solved the puzzle?","Does anybody know who invented the first bicycle?","After the rain there was a rainbow in the sky, wasn't it?","How dared you speak to me like that?"],correct:[0,1,2,4]},
  {opts:["The Nile's the longest river in the world, hasn't it?","When will be held the seminar?","Do you know that the ice on the Great Lakes breaks up in spring?","I suppose Mary will decorate the room, won't she?","How do you think he will react to this provocation?"],correct:[2,3,4]},
  {opts:["You like Italian food very much, don't you?","Nobody in the office could give you the information you needed, could they?","There's somebody calling your name, isn't he?","Do you like your new job or it's boring?","Did you use to eat a lot of chocolate when you were a child?"],correct:[0,1,4]},
  {opts:["What was doing Hans when you saw him?","Did this businessman use to be rich when he was young?","He's going to enter Medical College, hasn't he?","Can you tell me what do you know about dreams?","There's no information about it in this magazine, is there?"],correct:[1,4]},
  {opts:["Which hotel were the Blacks staying at?","Will there be any opportunity for them to start the course again?","How long did it take the Smiths to save money to buy that house?","Can you tell me what kind of food are you fond of?","The residence of the president of the USA is the White House, isn't he?"],correct:[0,1,2]},
  {opts:["Who helped them the difficulty to overcome?","Was it you who won the first prize?","Open the windows to air the room, will you?","It's the first time you have broken the law, hasn't it?","What do you think he knows about that case?"],correct:[1,2,4]},
  {opts:["Who did you talk to about your plans yesterday?","The packages just mailed at the post office will arrive on Monday, didn't they?","How many chapters does your graduation paper consist of?","Jack thinks I'll refuse his invitation, won't I?","Who do you think is the best player in your team?"],correct:[0,2,4]},
  {opts:["This instrument's grown out of use, hasn't it?","What made you accept his proposal?","The family's purchased a new car, isn't it?","Who are you making this cocktail for?","How dared your brother go there alone?"],correct:[0,1,3,4]},
  {opts:["Would you rather do the shopping now or after work?","It's hardly rained this autumn, is it?","That sofa needs cleaning, doesn't it?","Do you know why was Mark searching for a new apartment?","They have to receive a long-term loan, haven't they?"],correct:[0,1,2]},
  {opts:["Donald ought to help his parents, shouldn't he?","Who did you go to the discotheque with?","It's five years since they graduated, haven't they?","He's not seen my bike anywhere, is he?","Are there any women drivers among your friends?"],correct:[0,1,3,4]},
  {opts:["He had to meet his parents at the airport, didn't he?","How many greeting cards had typed the secretary by then?","Did you the terms discuss yesterday morning or not?","He promised to repay us within six months, didn't he?","Evergreen trees replace their leaves at specific times in the year, don't they?"],correct:[0,3,4]},
  {opts:["Why do you think he told such a terrible lie?","Is this the first or the second time you have driven a car?","Does Sarah at the University study medicine or law?","The police respond to emergencies in just a few minutes, don't they?","Can you tell me are you still corresponding with your former boyfriend?"],correct:[0,1,2,3]},
  {opts:["Which of you wants to take part in the discussion?","Her photograph corresponds with the description that he gave us, doesn't it?","Hasn't been Dan living in this district for ten years already?","She's got little money to buy that computer, has she?","The unions have reacted strongly against the government's wage and price controls, don't they?"],correct:[0,1,3]},
  {opts:["For who did you buy these flowers?","She's recommended as a suitable candidate for the job, isn't she?","Do you think they provided us a firm guarantee of quality?","He's not seen my keys anywhere, has he?","Do you know when are they coming to install the new cooker in the kitchen?"],correct:[1,3]},
  {opts:["Who usually goes shopping when you are not in town?","Are you or is your brother involved in politics?","The owner guaranteed the coins to be genuine, wasn't it?","His only interest was mathematics, wasn't he?","Do you know that behaviorism was one of the leading schools of psychological thought in the 20th century?"],correct:[0,1,4]},
  {opts:["This is the first time Henry has ridden a horse, isn't this?","Which of these two candidates appeals to you?","He's interested in art and music, isn't he?","How long had you been walking in the street when it started to snow?","Can you tell me what do you know about people called 'healers'?"],correct:[1,2,3]},
  {opts:["What is he looking at in admiration?","She didn't dare to open her mouth, did she?","The Smiths need two cars, needn't they?","Tom's got used to getting up early, hasn't he?","Do you know why bears sleep all winter?"],correct:[0,1,3,4]},
  {opts:["I believe Henry is a talented actor, don't I?","How dare you listen to a private conversation?","Have you sent out the greeting cards yet?","There are accidents every day at these crossroads, aren't they?","Who is Debbie chatting with?"],correct:[1,2,3,4]},
  {opts:["What did happen yesterday when I phoned you?","Do you know the harms that smoking causes?","I hope he's grown out of that bad habit, hasn't he?","Your garden fence needs repairing, needn't it?","Why he took Gulliver's Travels with him on his journey?"],correct:[1,2]},
  {opts:["Did Tom lose his job because he kept arriving late for work?","The police arrested the criminals yesterday, didn't it?","There's no money in this wallet, is it?","Help me alter this project, will you?","Did you know that air expands and becomes lighter when it's warmed?"],correct:[0,3,4]},
  {opts:["She's recommended him as a suitable candidate for that post, isn't she?","Do you know that light travels faster than sound?","It's difficult to decide between these two candidates, isn't it?","He's always been interested in literature, isn't he?","The concert ought to start at 7:30, oughtn't it?"],correct:[1,2,4]},
  {opts:["I think the car's suffered great damage, hasn't it?","Do you have any idea can we pay by credit card?","You think Mary will accept your proposal, don't you?","What did you use to do when you in Dresden lived?","Since when have you attended these courses?"],correct:[2,4]},
  {opts:["Were it you who signed those papers?","How long have you been working at this novel?","Is John a quick study, isn't he?","Do you know that the cheetah is the fastest animal?","This company has never provided a good service, has it?"],correct:[1,3,4]},
  {opts:["Have you registered for additional courses in Biology yet?","Can you tell me did you get used to the cold climate soon?","Does Mary usually go home after classes?","It's always been difficult for him to make a choice, hasn't it?","The boy's grown out of his clothes, isn't he?"],correct:[0,2,3]},
  {opts:["Did the Great Depression cause numerous problems to many farmers?","He's going to enter Law school, isn't he?","By what did you arrive in this city?","Do you know the harms that causes alcohol?","The head of the company's established his son in business, hasn't he?"],correct:[0,1,2]},
  {opts:["Which is more exciting: travelling by ship or by car?","It's ten years since we met last, isn't it?","Where will go your elder sister this summer?","How much time do you need to complete the work?","He drew a picture of a girl with flowers on her hat, wasn't she?"],correct:[0,1,3]},
  {opts:["What sports do you go in for?","Where will your children this winter go?","Did you have to wait for the bus long or it arrived soon?","There's been a very rich harvest this year, hasn't it?","She's got little time to spend with her children, has she?"],correct:[0,4]}
];


const SECTION_8_DATA = {
    questions: ALL_Q.map((item, index) => ({
        q: `${index + 1}. Select the correct statements:`,
        opts: item.opts
    })),
    answers: ALL_Q.map(item => {
        // Ստեղծում ենք 5 հատ false-ից բաղկացած զանգված
        let arr = [false, false, false, false, false];
        // Քո տված թվերի (ինդեքսների) տեղում դնում ենք true
        item.correct.forEach(i => {
            arr[i] = true;
        });
        return arr;
    })
};